### ISSUE TITLE
forge-essentials-1.8-1.8.0.12 CLIENT errors in console stream

### ISSUE THREAD

**Issue by kreezxil** [ForgeEssentials/FERemoteClient#4]
I'm using forge-essentials-1.8-1.8.0.12 on Forge b1498, during initialization the following errors appear multiple times in the console. The part that worries me is when "FORGE" says it will ignore FE. Apparently not the case tho as the clientside FE GUI is working and I can see all the pretty lines when I select something.

full fml client latest log: https://gist.github.com/kreezxil/8b8a4a00d027a662c0cb
```
[10:42:02] [main/ERROR] [DepLoader/]: Failed to load dependencies.info from forge-essentials-1.8-1.8.0.12.jar as JSON
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_51]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_51]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_51]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_51]
	at codechicken.core.launch.DepLoader$DepLoadInst.scanDepInfo(DepLoader.java:600) [DepLoader$DepLoadInst.class:?]
	at codechicken.core.launch.DepLoader$DepLoadInst.scanDepInfos(DepLoader.java:593) [DepLoader$DepLoadInst.class:?]
	at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:491) [DepLoader$DepLoadInst.class:?]
	at codechicken.core.launch.DepLoader.load(DepLoader.java:684) [DepLoader.class:?]
	at codechicken.core.launch.CodeChickenCorePlugin.<init>(CodeChickenCorePlugin.java:47) [%5B0%5DCodeChickenCore-1.8-1.0.5.36-universal.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) [?:1.8.0_51]
	at java.lang.Class.newInstance(Unknown Source) [?:1.8.0_51]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:526) [modpack.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:409) [modpack.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:241) [modpack.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [modpack.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [modpack.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [modpack.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [modpack.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```
and

```
[10:42:07] [main/ERROR] [FML/]: Unable to read the jar file forge-essentials-1.8-1.8.0.12.jar - ignoring
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_51]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_51]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_51]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_51]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_51]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:328) [modpack.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:241) [modpack.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [modpack.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [modpack.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [modpack.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [modpack.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by aschmois** [comment]
This is not related to FE at all. You should redownload FE because it seems like it's corrupt. The actual error is a codechicken core mod problem

**Comment by kreezxil** [comment]
Where in those error fragments do you get that it is not your mod? I would like to know how you determined it was the chickencore? That way I can hone my error parsing skills. Thanks in advance.

**Comment by luacs1998** [comment]
```
...
 at codechicken.core.launch.DepLoader$DepLoadInst.scanDepInfo(DepLoader.java:600) [DepLoader$DepLoadInst.class:?]
...
```

**Comment by olee** [comment]
Btw this issue was not related at all to FERemoteClient... be sure to post correctly at ForgeEssentialsMain next time :wink:
